### ISSUE TITLE
Follow up on Programming usage increase question/plot

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [carpentries/assessment-projects#12]
Two ideas, 

Given the dramatic increase for the daily use, would be nice to know in the future, or maybe we can dig on how much of this increase is because of the workshop. Maybe we can ask why folks took the workshop, were they about to start a career, semester, project? 

Also, should we have some testing here to demonstrate which before/after differences are significant?

**Comment by JasonJWilliamsNY** [comment]
Ok. I should think about reading before I speak. 

I do see the next plot on Chi-squared residuals. I am not in this field so perhaps this is the standard? For me, I would just have liked to know which of the first plot (bar plot) were significant.

**Comment by kariljordan** [comment]
@JasonJWilliamsNY We are unable to pair the long-term responses with the responses from the post-workshop survey they took six months to a year ago (when they took their workshop) because we did not have them select a unique identifier. This is something we will be able to do moving forward, however, for Data Carpentry. Our current [survey](https://github.com/carpentries/assessment-projects/blob/master/data-carpentry-projects/postsurvey.pdf) asks learners to create a unique ID that they will also enter when they take the post-survey. That way we'll be able to pair the data. All we can do now is make general comparisons about the results from this survey and those of DC and SwC.

@benmarwick created the Chi-squared residual plot. It's a good way to show compare what we observed to what we expected to observe. Ben, help me if that's not a good way to explain it:) We include the pre/post bar plot before the chi-square to help show the difference in their self-reported programming before and six months after the workshop as well.
